(()=>{
'use strict';
const BOOT=window.PRISMA_DEMO_BOOT;delete window.PRISMA_DEMO_BOOT;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={book:'<path d="M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-3H4zM20 4h-4a3 3 0 0 0-3 3v14a4 4 0 0 1 4-3h3z"/>',chat:'<path d="M21 11a9 9 0 0 1-9 9H5l-3 2 1.5-5A9 9 0 1 1 21 11Z"/><path d="M8 11h.01M12 11h.01M16 11h.01"/>',network:'<path d="M9.5 10.5 5.5 6.5M14.5 10.5l4-4M9.5 13.5l-4 4M14.5 13.5l4 4M12 9V5M12 15v4"/><circle cx="12" cy="12" r="3"/><circle cx="4" cy="5" r="2"/><circle cx="20" cy="5" r="2"/><circle cx="4" cy="19" r="2"/><circle cx="20" cy="19" r="2"/><path d="M10 3h4M10 21h4"/>',chevron:'<path d="m6 9 6 6 6-6"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',shield:'<path d="M12 3l8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3z"/><path d="m8 12 3 3 5-6"/>',chart:'<path d="M3 3v18h18M7 15l4-5 4 3 5-7"/>',spark:'<path d="m12 3 2.2 6.8L21 12l-6.8 2.2L12 21l-2.2-6.8L3 12l6.8-2.2z"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M5 17v4h14v-4"/>',refresh:'<path d="M20 7v5h-5M4 17v-5h5M7 5a8 8 0 0 1 13 7M4 12a8 8 0 0 0 13 7"/>',database:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',panel:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16m5-11-3 3 3 3"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',phone:'<path d="M8 3H4a1 1 0 0 0-1 1c0 9.4 7.6 17 17 17a1 1 0 0 0 1-1v-4l-5-2-2 3a15 15 0 0 1-7-7l3-2z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5 19 19M5 19l1.5-1.5M17.5 6.5 19 5"/>',moon:'<path d="M21 12.8A9 9 0 0 1 11.2 3 9 9 0 1 0 21 12.8z"/>',monitor:'<rect x="3" y="3" width="18" height="14" rx="2"/><path d="M12 17v4M8 21h8"/>'};
const icon=n=>'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">'+(paths[n]||paths.info)+'</svg>';
const prismaMark=()=>"<svg class=\"prisma-symbol\" viewBox=\"0 0 64 64\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\"><path d=\"M2 23 18 30\" fill=\"none\" stroke=\"#b5687a\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M2 33 16 34\" fill=\"none\" stroke=\"#6e97bd\" stroke-width=\"2\" stroke-linecap=\"round\"/><path d=\"M2 43 13 39\" fill=\"none\" stroke=\"#72a893\" stroke-width=\"2\" stroke-linecap=\"round\"/><polygon points=\"29,10 36,7 55,47 48,50\" fill=\"currentColor\" fill-opacity=\".13\" stroke=\"currentColor\" stroke-opacity=\".62\" stroke-width=\"1.3\" stroke-linejoin=\"round\"/><polygon points=\"10,50 48,50 55,47 17,47\" fill=\"currentColor\" fill-opacity=\".09\" stroke=\"currentColor\" stroke-opacity=\".5\" stroke-width=\"1.3\" stroke-linejoin=\"round\"/><polygon data-face=\"front\" points=\"10,50 29,10 48,50\" fill=\"#edf5fa\" fill-opacity=\".2\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linejoin=\"round\"/><path d=\"M18 44 29 19\" fill=\"none\" stroke=\"currentColor\" stroke-opacity=\".24\" stroke-width=\"1.2\" stroke-linecap=\"round\"/><path d=\"M47 33H63\" fill=\"none\" stroke=\"currentColor\" stroke-opacity=\".75\" stroke-width=\"2.2\" stroke-linecap=\"round\"/></svg>";
const domains={core:{label:'ERP Core',key:'core',icon:'database',eyebrow:'A referência de origem',description:'Empresa e cliente preservam o contexto do cadastro fictício.'},crm:{label:'CRM',key:'crm',icon:'users',eyebrow:'Relacionamento organizado',description:'Propriedades comerciais e referências explícitas em uma fonte sintética.'},omnichannel:{label:'Omnichannel',key:'omni',icon:'chat',eyebrow:'Relacionamento em cada canal',description:'Contatos, conversas e mensagens criados do zero para o portfólio.'},prisma:{label:'Prisma',key:'prisma',icon:'network',eyebrow:'Perspectivas que se encontram',description:'Conciliação explicável com origem preservada. Nenhuma pessoa é unida automaticamente.'}};
const pages=[['Resumo','grid'],['Cadastros','users'],['Qualidade dos dados','shield'],['Conciliação','network'],['Conversas','chat'],['Snapshots','download'],['Documentação e regras','book']];
const qp=new URLSearchParams(location.search),sysTheme=matchMedia('(prefers-color-scheme:dark)');
let preference='escuro';try{preference=localStorage.getItem('prisma.demo.theme.v1')||preference}catch{}
if(['claro','escuro','sistema'].includes(qp.get('tema')))preference=qp.get('tema');
if(!['claro','escuro','sistema'].includes(preference))preference='escuro';
const S={source:domains[qp.get('fonte')]&&qp.get('fonte')!=='prisma'?qp.get('fonte'):'core',page:pages.some(p=>p[0]===qp.get('pagina'))?qp.get('pagina'):'Conciliação',collapsed:true,mobile:false,docDomain:domains[qp.get('area')]?qp.get('area'):'prisma',overview:null,payload:null,loading:true,error:'',search:'',issue:'all',status:'all',pageNumber:1,size:25,reveal:false};
let generation=0,toastTimer;const labels={confirmed_by_reference:'Pela referência',candidate:'Candidato',conflict:'Conflito',not_found:'Não encontrado',not_comparable:'Não comparável',not_evaluated:'Não avaliado'};
const explanations={confirmed_by_reference:'Referência Core explícita, única e sem contato apontando outro destino. Resultado da regra no snapshot; não é validação civil.',candidate:'Contato coincidente sem confirmação por referência. Não une pessoas nem autoriza atualização.',conflict:'Chaves apontam múltiplos destinos, contatos compartilhados ou evidências divergentes. Revisão necessária.',not_found:'Sem coincidência nas chaves utilizáveis desta cópia. Não é ausência confirmada em tempo real.',not_comparable:'Sem chaves utilizáveis para avaliar presença ou ausência.',not_evaluated:'Fonte indisponível; nenhum resultado de presença/ausência foi inferido.'};
const num=v=>v===null||v===undefined?'Não disponível':new Intl.NumberFormat('pt-BR').format(v);
const stamp=v=>v?new Date(v).toLocaleString('pt-BR',{timeZone:'UTC'})+' UTC':'Não disponível';
const domainFor=source=>domains[source]||domains.prisma;const context=()=>S.page==='Documentação e regras'?domains[S.docDomain]:domains.prisma;
const query=o=>new URLSearchParams(o).toString();
async function api(path){const response=await fetch(path,{headers:{'X-Prisma-Demo-Token':BOOT.token},cache:'no-store'});let body;try{body=await response.json()}catch{throw Error('Resposta local inválida. Recarregue o painel.')}if(!response.ok)throw Error(body.error||'Falha na leitura dos snapshots.');return body}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000)}
function table(headers,rows,compact=false){return '<div class="table-scroll"><table class="data-table live-table demo-table '+(compact?'demo-compact':'')+'"><thead><tr>'+headers.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><p class="demo-scroll-hint">Deslize a tabela para ver todas as colunas ↔</p>'}
function card(title,body,badge=''){return '<section class="card glass-panel"><div class="card-header"><h2>'+esc(title)+'</h2>'+(badge?'<span class="badge">'+esc(badge)+'</span>':'')+'</div><div class="card-body">'+body+'</div></section>'}
function notice(text,warn=false){return '<div class="live-alert '+(warn?'warning':'')+' demo-warning">'+esc(text)+'</div>'}
function button(action,text,value='',cls='live-button'){return '<button type="button" class="'+cls+'" data-action="'+action+'" data-value="'+esc(value)+'">'+text+'</button>'}
function status(code){return '<span class="demo-status" data-status="'+esc(code)+'">'+esc(labels[code]||code)+'</span>'}
function revealControl(){return '<label class="demo-check"><input id="reveal" type="checkbox" '+(S.reveal?'checked':'')+'>Mostrar os dados fictícios sem máscara — nenhum registro é real</label>'}
function metrics(items){return '<div class="demo-metrics">'+items.map(([title,value,note])=>'<section class="demo-metric glass-panel"><h2>'+esc(title)+'</h2><strong>'+num(value)+'</strong><p>'+esc(note)+'</p></section>').join('')+'</div>'}
function sourceTable(){const o=S.overview;return table(['Fonte','Disponibilidade','Registros','Snapshot'],['core','crm','omnichannel'].map(s=>{const source=o.sources[s];return [esc(source.label),source.available?'Disponível':'Não disponível',num(source.profile?.records),esc(stamp(source.snapshot_at))]}))}
function themes(){return '<div class="theme-control"><select id="theme-select" aria-label="Tema da interface">'+[['claro','Claro'],['escuro','Escuro'],['sistema','Sistema']].map(([v,l])=>'<option value="'+v+'" '+(preference===v?'selected':'')+'>'+l+'</option>').join('')+'</select></div>'}
function applyTheme(p,save=false){preference=p;const dark=p==='escuro'||p==='sistema'&&sysTheme.matches;document.documentElement.dataset.opcao=dark?'nocturne':'aurora';document.documentElement.dataset.themePreference=p;if(save)try{localStorage.setItem('prisma.demo.theme.v1',p)}catch{toast('Preferência de tema válida somente nesta sessão.')}if($('#theme-select'))$('#theme-select').value=p;syncSelects()}
sysTheme.addEventListener('change',()=>{if(preference==='sistema')applyTheme(preference)});
function sourceMenu(){return '<div class="nav-source"><span class="nav-label source-caption">Fonte fictícia</span><select id="source-select" aria-label="Fonte sintética">'+['core','crm','omnichannel'].map(s=>'<option value="'+s+'" '+(S.source===s?'selected':'')+'>'+esc(domains[s].label)+'</option>').join('')+'</select></div>'}
function nav(){return '<nav class="navigation" aria-label="Navegação principal"><div class="nav-top"><div class="mark prisma-mark">'+prismaMark()+'</div><div class="wordmark"><strong>Prisma</strong><small>Demo · somente leitura</small></div></div>'+sourceMenu()+'<div class="nav-scroll">'+pages.map(([page,glyph])=>'<button class="nav-item '+(S.page===page?'active':'')+'" data-action="page" data-value="'+page+'" title="'+page+'" '+(S.page===page?'aria-current="page"':'')+'>'+icon(glyph)+'<span class="nav-label">'+page+'</span></button>').join('')+'</div><div class="nav-bottom"><button data-action="collapse" aria-label="'+(S.mobile?'Fechar navegação':S.collapsed?'Fixar navegação expandida':'Recolher navegação')+'">'+icon('panel')+'<span class="nav-label">'+(S.mobile?'Fechar menu':S.collapsed?'Fixar expandida':'Recolher menu')+'</span></button></div></nav>'}
function spectrum(){return '<div class="spectrum-trail" aria-label="Perspectivas"><span data-domain="omni">'+icon('chat')+'Omnichannel</span><span data-domain="crm">'+icon('users')+'CRM</span><span data-domain="core">'+icon('database')+'ERP Core</span><span class="trail-result" data-domain="prisma">'+icon('network')+'Prisma</span></div>'}
function pager(){const p=S.payload;if(!p?.pages)return '';return '<div class="demo-pager"><span class="demo-notes">'+num(p.total)+' registros · página '+p.page+' de '+p.pages+'</span><div class="buttons"><button class="live-button" data-action="previous" '+(p.page<=1?'disabled':'')+'>Anterior</button><button class="live-button" data-action="next" '+(p.page>=p.pages?'disabled':'')+'>Próxima</button></div></div>'}
function filters(kind){let options='';if(kind==='records')options=Object.entries(S.overview.issues).map(([k,v])=>'<option value="'+k+'" '+(S.issue===k?'selected':'')+'>'+esc(v)+'</option>').join('');else if(kind==='reconciliation')options='<option value="all">Todas</option>'+Object.entries(labels).map(([k,v])=>'<option value="'+k+'" '+(S.status===k?'selected':'')+'>'+esc(v)+'</option>').join('');return '<form id="filters" class="demo-filters" data-kind="'+kind+'"><label><span>Buscar nome fictício, ID ou chave</span><input id="search" type="search" maxlength="200" value="'+esc(S.search)+'" placeholder="'+esc(kind==='conversations'?'Ex.: DEMO-CONV-00001':kind==='records'?'Ex.: DEMO-'+({core:'CORE',crm:'CRM',omnichannel:'OMNI'}[S.source])+'-00008':'Ex.: DEMO-CORE-00008')+'"></label>'+(options?'<label><span>'+(kind==='records'?'Fila de qualidade':'Situação em qualquer destino')+'</span><select id="filter-select">'+options+'</select></label>':'<p class="demo-notes">Busca nas conversas fictícias.</p>')+'<button type="submit" class="live-button">Aplicar filtros</button></form>'}
function summaryPage(){const o=S.overview,m=o.core_metrics;return metrics([['Universo Core',m?.total,'Cadastros de referência, sem somar as fontes'],['Referência nos dois',m?.reference_both,'Resultado da regra nos snapshots'],['Exigem revisão',m?.review,'Core com candidato ou conflito em algum destino']])+card('Três fontes. Uma leitura rastreável.',sourceTable())+notice('Ambiente de portfólio: banco e API fictícios. Este painel lê somente os snapshots extraídos, com SHA-256 verificado. Não consulta a organização.')+resultsTable()+card('Como explorar a demonstração','<p class="demo-notes">Busque DEMO-CORE-00008 em Conciliação para ver evidências conflitantes; DEMO-CORE-00002 representa um candidato por contato. As duas empresas compartilham um ID local em um cenário controlado.</p>'+button('page','Abrir conciliação '+icon('arrow'),'Conciliação'))}
function resultsTable(){const results=S.overview.results;if(!results)return notice('ERP Core indisponível: não existe universo para comparar.',true);return card('Resultados por destino',table(['Regra no snapshot','CRM','Omnichannel'],Object.entries(labels).map(([key,label])=>[esc(label),num(results.crm[key]||0),num(results.omnichannel[key]||0)]),true)+'<p class="demo-notes">Cada coluna usa o mesmo universo Core. Não somar as relações como pessoas únicas. Os horários das cópias diferem; não são resultados em tempo real.</p>')}
function reconciliationPage(){const p=S.payload;if(!p?.available)return notice(p?.message||'Universo Core indisponível.',true)+card('Disponibilidade das fontes',sourceTable());return notice('ERP Core é a referência. Contato coincidente produz candidato, nunca união automática. “Pela referência” é uma regra no snapshot, não validação civil.')+card('Cobertura da leitura local',sourceTable())+card('Onde está cada cadastro?',filters('reconciliation')+revealControl()+table(['ERP Core · referência','CRM','Omnichannel','Evidência'],p.rows.map(r=>['<strong>'+esc(r.id)+'</strong><small>'+esc(r.name)+'</small><small>'+esc(r.company_id)+' / '+esc(r.customer_id)+'</small>',status(r.crm.status)+'<small>'+r.crm.candidates.length+' destino(s) por chave</small>',status(r.omnichannel.status)+'<small>'+r.omnichannel.candidates.length+' destino(s) por chave</small>',button('evidence','Ver chaves '+icon('arrow'),r.id,'evidence-button')]))+(!p.rows.length?'<p class="demo-empty">Nenhum cadastro corresponde aos filtros.</p>':'')+pager())+resultsTable()}
function recordsPage(){const p=S.payload;return card(domains[S.source].label+' · cadastros fictícios',filters('records')+revealControl()+table(['ID nativo','Nome','E-mail','Telefone fictício','Referência Core','Pendências'],p.rows.map(r=>[esc(r.id),esc(r.name),esc(r.email||'Ausente'),esc(r.phone||'Ausente'),esc(r.core_reference||'Não mapeada'),esc(r.issues.map(k=>S.overview.issues[k]).join(' · ')||'Nenhuma destas filas')]))+(!p.rows.length?'<p class="demo-empty">Nenhum registro corresponde aos filtros.</p>':'')+pager())}
function qualityPage(){const p=S.overview.sources[S.source].profile;if(!p)return notice('Fonte sintética indisponível. Não exibir ausência como zero.',true);return metrics([['Registros',p.records,domains[S.source].label+' · apenas esta fonte'],['E-mails na sintaxe',p.email_syntax,'Não comprova entrega ou titularidade'],['Telefones preenchidos',p.phone_filled,'DDD 00: fictícios e não discáveis']])+notice('Diagnóstico de uma base fictícia. As filas podem se sobrepor; não somar como pessoas ou como registros únicos.')+card('Filas de qualidade',table(['Fila','Registros','Consultar'],Object.entries(p.issues).filter(([key])=>S.source!=='core'||key!=='missing_reference').map(([key,value])=>[esc(S.overview.issues[key]),num(value),button('queue','Ver registros',key)]),true))+card('Identificação e limites',table(['Campo/regra','Leitura'],[['Documentos ausentes',p.document_missing===null?'Não modelado nesta fonte':num(p.document_missing)],['Documentos inválidos',p.document_invalid===null?'Não modelado nesta fonte':num(p.document_invalid)],['Referência Core preenchida',num(p.reference_filled)],['E-mail compartilhado',num(p.shared_email_records)+' registros com valor repetido na fonte']].map(r=>r.map(esc)),true)+'<p class="demo-notes">Todos os documentos da demo são vazios ou explicitamente inválidos. Não existe confirmação por CPF nesta versão. Campo não modelado não é zero.</p>')}
function conversationsPage(){const p=S.payload;return notice('Conversas e mensagens criadas do zero. Não são cópias nem anonimização de atendimentos internos.')+card('Histórico de atendimento fictício',filters('conversations')+table(['Conversa','Cliente Omnichannel','Canal','Estado','Mensagens'],p.rows.map(r=>[esc(r.id),esc(r.customer_id),esc(r.channel),r.status==='closed'?'Concluída':'Em andamento',button('messages','Abrir histórico '+icon('arrow'),r.id)]))+(!p.rows.length?'<p class="demo-empty">Nenhuma conversa corresponde à busca.</p>':'')+pager())}
function snapshotsPage(){const o=S.overview;return notice('Leitura imutável desta extração. Para usar outra extração, pare o painel e reinicie com --snapshots apontando para a pasta nova.')+card('Disponibilidade e momento de cada fonte',sourceTable())+card('Integridade verificada',table(['Arquivo','SHA-256 verificado'],Object.entries(o.hashes).map(([name,hash])=>[esc(name),'<span class="demo-hash">'+esc(hash)+'</span>']))+'<p class="demo-notes">Hashes detectam alterações em relação ao manifesto; não provam por si só a origem sintética. O carregador também valida as convenções dos registros.</p>')+card('Identidade desta extração','<p class="demo-notes">Dataset</p><p class="demo-hash">'+esc(o.dataset)+'</p><p class="demo-notes">Carregado em '+esc(stamp(o.loaded_at))+'. Nenhum acesso ao banco/API operacional.</p>')}
const rules={
 core:[['Empresa + cliente','A chave Core preserva o contexto da empresa. O mesmo ID local aparece em duas empresas fictícias e não deve ser unido.'],['Universo de referência','A conciliação começa nos cadastros Core. Core indisponível impede definir o universo; isso não significa zero clientes.'],['Documentos','Os documentos são vazios ou explicitamente inválidos. Não há confirmação por CPF nem vínculo civil.']],
 crm:[['Propriedades explícitas','Os snapshots mantêm o envelope properties do contrato público. core_reference é uma referência opcional, não o ID nativo CRM.'],['Paginação e cópia','O extrator percorre cursores, verifica IDs e escreve snapshots com hashes. O painel não faz sincronização automática.'],['Dados comerciais fictícios','Stages lead, qualified e customer foram gerados para portfólio. Não representam conversão, consentimento ou resultados internos.']],
 omnichannel:[['Contatos compartilhados','E-mail ou telefone coincidente pode pertencer a vários cadastros. A demo preserva os candidatos e evidencia conflitos.'],['Conversas e mensagens','Texto, roteamento e estados são exemplos gerados do zero. Mensagens só podem referenciar conversas existentes.'],['Momentos distintos','O snapshot Omnichannel é anterior às outras cópias por construção. Isso limita conclusões sobre presença atual.']],
 prisma:[['Evidência antes de conclusão','Referência única e consistente pode produzir resultado pela regra. Contato isolado permanece candidato; múltiplos destinos exigem revisão.'],['Comparador público simplificado','Esta versão conecta os snapshots ao validador demo. Não substitui o motor operacional completo nem trata confirmação por documento ou score.'],['Separação operacional','O painel não carrega .env, credenciais ou módulos privados. Não importa bases reais, não escreve entre fontes e não envia mensagens.']]};
function docsPage(){const d=domains[S.docDomain];return '<div class="docs-nav" aria-label="Perspectivas da documentação">'+['omnichannel','crm','core','prisma'].map(key=>{const domain=domains[key];return '<button class="domain-tab '+(key===S.docDomain?'selected':'')+'" data-domain="'+domain.key+'" data-action="domain" data-value="'+key+'" aria-pressed="'+(key===S.docDomain)+'">'+icon(domain.icon)+'<span>'+domain.label+'<small>'+(key==='prisma'?'Painel central':'Fonte sintética')+'</small></span></button>'}).join('')+'</div>'+card(d.label+' · documentação e regras','<ul class="demo-doc-rules">'+rules[S.docDomain].map(([title,text])=>'<li><strong>'+esc(title)+'</strong><p>'+esc(text)+'</p></li>').join('')+'</ul>','Contrato público')+card('Fluxo de demonstração','<p class="demo-contract"><code>Gerador sintético → SQLite → API local → extrator → snapshots → painel Prisma</code></p><p class="demo-notes">A API (porta 8787) só é necessária para gerar a extração. O painel (porta 8790) funciona offline depois que os snapshots existem. Não há dependência do projeto operacional.</p>')}
function loadingPage(){return '<section class="loading-panel" role="status" aria-live="polite"><div class="loading-status"><span class="loading-spinner" aria-hidden="true"></span><div><h2>Prisma está preparando a leitura demo…</h2><p>Carregando os snapshots fictícios verificados. Nenhum serviço da organização é acessado.</p></div></div><div class="skeleton-metrics" aria-hidden="true">'+Array.from({length:3},()=>'<div class="skeleton-card"><span class="skeleton-line short"></span><span class="skeleton-line number"></span><span class="skeleton-line"></span></div>').join('')+'</div></section>'}
function body(){if(S.loading)return loadingPage();if(S.error)return notice(S.error,true)+button('reload','Tentar novamente')+button('page','Ver disponibilidade','Resumo');return {'Resumo':summaryPage,'Cadastros':recordsPage,'Qualidade dos dados':qualityPage,'Conciliação':reconciliationPage,'Conversas':conversationsPage,'Snapshots':snapshotsPage,'Documentação e regras':docsPage}[S.page]()}
function render(){closeSelect(false);document.body.classList.toggle('collapsed',S.collapsed);document.body.classList.toggle('mobile-open',S.mobile);const d=context(),docs=S.page==='Documentação e regras';document.documentElement.dataset.visual=d.key;document.documentElement.dataset.source=domainFor(S.source).key;const title=docs?d.label+' · documentação':S.page==='Resumo'?'Fontes distintas. Decisões claras.':S.page;$('#app').innerHTML='<div class="shell"><button class="scrim" data-action="menu" aria-label="Fechar navegação"></button>'+nav()+'<main class="main" id="conteudo" tabindex="-1" aria-busy="'+S.loading+'"><div class="topline"><div class="breadcrumb"><button class="icon-button mobile-nav" data-action="menu" aria-label="Abrir navegação">'+icon('menu')+'</button><span class="prefix">Prisma /</span><strong>'+esc(S.page)+'</strong></div><div class="toolbar"><span class="badge">Snapshots fictícios</span>'+themes()+button('help',icon('info'),'','icon-button')+'</div></div><div class="intro-row prisma-intro"><div class="intro"><div class="eyebrow"><span class="line"></span>'+esc(docs?d.eyebrow:'ERP Core → CRM · Omnichannel')+'</div><h1>'+esc(title)+'</h1><p>'+esc(docs?d.description:S.page==='Conciliação'?'O cadastro Core como referência. Veja quais chaves sustentam a leitura e o que exige revisão.':'Uma demonstração de qualidade e conciliação inteiramente sintética, com origem e limites explícitos.')+'</p></div><span class="example-chip">'+icon('shield')+'Demo · somente leitura</span></div>'+(!docs&&['Resumo','Conciliação'].includes(S.page)?spectrum():'')+body()+'<footer class="approval-note"><p><strong>Prisma Demo 0.3.1</strong> · dados gerados do zero.<br>Sem credenciais, consultas externas ou união automática.</p>'+button('page','Documentação e regras '+icon('book'),'Documentação e regras')+'</footer></main></div>';$('#app [data-action="help"]')?.setAttribute('aria-label','Metodologia e segurança');upgradeSelects();applyTheme(preference)}
async function hydrate(){const gen=++generation;S.loading=true;S.error='';render();try{const overview=await api('/api/panel/overview');let payload=null;const common={search:S.search,page:S.pageNumber,size:S.size,reveal:S.reveal?'1':'0'};if(S.page==='Conciliação')payload=await api('/api/panel/reconciliation?'+query({...common,status:S.status}));if(S.page==='Cadastros')payload=await api('/api/panel/records?'+query({...common,source:S.source,issue:S.issue}));if(S.page==='Conversas')payload=await api('/api/panel/conversations?'+query(common));if(gen!==generation)return;Object.assign(S,{overview,payload,loading:false});if(payload?.page)S.pageNumber=payload.page;render()}catch(e){if(gen!==generation)return;S.loading=false;S.error=e.message;render()}}
function showDialog(title,content){const d=$('#dialog');d.innerHTML='<div class="dialog-head"><h2>'+esc(title)+'</h2>'+button('close',icon('close'),'','icon-button')+'</div>'+content;d.querySelector('[data-action="close"]').setAttribute('aria-label','Fechar detalhes');if(!d.open)d.showModal()}
async function evidence(id){try{const row=await api('/api/panel/evidence?'+query({id,reveal:S.reveal?'1':'0'}));let html='<p class="demo-notes">'+esc(row.id)+' · '+esc(row.name)+'<br>Referência: '+esc(row.core_reference)+'</p>';for(const source of ['crm','omnichannel']){const outcome=row[source];html+=card(domains[source].label,status(outcome.status)+'<p class="demo-notes">'+esc(explanations[outcome.status])+'</p>'+outcome.candidates.map(c=>'<h3>'+esc(c.id)+' · '+esc(c.name)+'</h3>'+table(['Chave','Valor','Ocorrências Core','Ocorrências destino'],c.keys.map(k=>[esc({core_reference:'Referência Core',email:'E-mail',phone:'Telefone'}[k.kind]),esc(k.value),num(k.core_occurrences),num(k.source_occurrences)]),true)).join('')+(!outcome.candidates.length?'<p class="demo-empty">Nenhum candidato listado para esta fonte.</p>':''))}showDialog('Evidências da conciliação',html)}catch(e){toast(e.message)}}
async function messages(id){try{const p=await api('/api/panel/messages?'+query({id}));showDialog('Histórico fictício · '+id,'<ol class="demo-timeline">'+p.rows.map(r=>'<li class="demo-message"><strong>'+esc({customer:'Cliente fictício',agent:'Atendente fictício',system:'Sistema demo'}[r.sender])+'</strong><br><small>'+esc(stamp(r.created_at))+'</small><p>'+esc(r.text)+'</p></li>').join('')+'</ol>')}catch(e){toast(e.message)}}
function navigate(page){if(!pages.some(p=>p[0]===page))return;S.page=page;S.pageNumber=1;S.search='';S.issue='all';S.status='all';S.mobile=false;window.scrollTo({top:0});hydrate()}
document.addEventListener('click',e=>{const control=e.target.closest('[data-action]');if(!control)return;const action=control.dataset.action,value=control.dataset.value;if(action==='page')navigate(value);else if(action==='collapse'){if(S.mobile)S.mobile=false;else S.collapsed=!S.collapsed;render()}else if(action==='menu'){S.mobile=!S.mobile;render()}else if(action==='reload')hydrate();else if(action==='next'||action==='previous'){S.pageNumber+=action==='next'?1:-1;hydrate();window.scrollTo({top:0})}else if(action==='queue'){S.issue=value;S.page='Cadastros';S.pageNumber=1;S.search='';hydrate()}else if(action==='domain'){S.docDomain=value;render()}else if(action==='evidence')evidence(value);else if(action==='messages')messages(value);else if(action==='close')$('#dialog').close();else if(action==='help')showDialog('Metodologia e segurança',notice('DEMO: apenas dados fictícios e snapshots verificados. Não publicar esta instância local na internet.',true)+'<p class="demo-contract">O painel usa adaptadores públicos separados do ambiente operacional. SHA-256, IDs DEMO, domínios example.test e convenções sintéticas são verificados antes da carga. O marcador synthetic não é, isoladamente, prova de origem.</p><p class="demo-contract">O comparador é simplificado: preserva candidatos e conflitos, sem documentos válidos, score, autenticação multiusuário ou escrita. Os horários dos snapshots diferem; não comprova identidade civil, consentimento nem presença em tempo real.</p>')});
document.addEventListener('change',e=>{if(e.target.id==='source-select'){S.source=e.target.value;S.pageNumber=1;S.search='';S.issue='all';hydrate()}else if(e.target.id==='theme-select')applyTheme(e.target.value,true);else if(e.target.id==='reveal'){S.reveal=e.target.checked;hydrate()}});
document.addEventListener('submit',e=>{if(e.target.id!=='filters')return;e.preventDefault();S.search=$('#search').value;S.pageNumber=1;if(S.page==='Cadastros')S.issue=$('#filter-select').value;else if(S.page==='Conciliação')S.status=$('#filter-select').value;hydrate()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&S.mobile){S.mobile=false;render()}});
let activeSelect=null;
function closeSelect(focus=true){const active=activeSelect;activeSelect=null;$('#select-popup')?.remove();document.body.classList.remove('select-open');if(active){active.button.setAttribute('aria-expanded','false');if(focus&&active.button.isConnected)active.button.focus()}}
function selectIcon(select){return select.id==='source-select'?'database':select.id==='theme-select'?(preference==='sistema'?'monitor':preference==='claro'?'sun':'moon'):null}
function syncSelects(){document.querySelectorAll('select[data-enhanced]').forEach(select=>{const button=select.nextElementSibling?.querySelector('.select-trigger');if(!button)return;const glyph=selectIcon(select);button.innerHTML=(glyph?icon(glyph):'')+'<span class="select-text">'+esc(select.selectedOptions[0]?.textContent||'Selecionar')+'</span>'+icon('chevron');button.disabled=select.disabled})}
function openSelect(select,button){const repeat=activeSelect?.select===select;closeSelect(false);if(repeat)return;activeSelect={select,button};if(select.id==='source-select')document.body.classList.add('select-open');button.setAttribute('aria-expanded','true');const menu=document.createElement('div');menu.id='select-popup';menu.className='select-popup';menu.setAttribute('role','listbox');menu.setAttribute('aria-label',button.getAttribute('aria-label'));menu.innerHTML=[...select.options].map((o,i)=>'<button type="button" role="option" data-index="'+i+'" aria-selected="'+o.selected+'" '+(o.disabled?'disabled':'')+'><span>'+esc(o.textContent)+(o.dataset.description?'<small>'+esc(o.dataset.description)+'</small>':'')+'</span><span class="select-check" aria-hidden="true">'+(o.selected?'✓':'')+'</span></button>').join('');document.body.append(menu);const rect=button.getBoundingClientRect(),width=Math.min(Math.max(rect.width,select.id==='source-select'?248:200),innerWidth-32);menu.style.width=width+'px';menu.style.left=Math.max(16,Math.min(rect.left,innerWidth-width-16))+'px';const bottomSpace=innerHeight-rect.bottom-24;menu.style.maxHeight=Math.max(120,Math.min(320,Math.max(bottomSpace,rect.top-24)))+'px';if(bottomSpace>=Math.min(250,menu.scrollHeight))menu.style.top=(rect.bottom+8)+'px';else menu.style.bottom=(innerHeight-rect.top+8)+'px';menu.querySelector('[aria-selected="true"]')?.focus();menu.addEventListener('click',e=>{const item=e.target.closest('[data-index]');if(!item||item.disabled)return;select.selectedIndex=Number(item.dataset.index);closeSelect();syncSelects();select.dispatchEvent(new Event('change',{bubbles:true}))});menu.addEventListener('keydown',e=>{const items=[...menu.querySelectorAll('button:not(:disabled)')],index=items.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();items[e.key==='Home'?0:e.key==='End'?items.length-1:(index+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus()}else if(e.key==='Escape'){e.preventDefault();closeSelect()}else if(e.key==='Tab')closeSelect(false)})}
function upgradeSelects(){document.querySelectorAll('select:not([data-enhanced])').forEach(select=>{select.dataset.enhanced='true';select.hidden=true;const wrap=document.createElement('div');wrap.className='ui-select';const button=document.createElement('button');button.type='button';button.className='select-trigger';button.setAttribute('aria-haspopup','listbox');button.setAttribute('aria-expanded','false');button.setAttribute('aria-controls','select-popup');button.setAttribute('aria-label',select.getAttribute('aria-label')||select.closest('label')?.childNodes[0]?.textContent.trim()||'Selecionar opção');wrap.append(button);select.after(wrap);button.addEventListener('click',e=>{e.preventDefault();openSelect(select,button)});button.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();openSelect(select,button)}})});syncSelects()}
document.addEventListener('pointerdown',e=>{if(activeSelect&&!e.target.closest('#select-popup')&&!activeSelect.button.contains(e.target))closeSelect(false)});
window.addEventListener('resize',()=>closeSelect(false));
window.addEventListener('scroll',e=>{if(activeSelect&&e.target!==$('#select-popup')&&!$('#select-popup')?.contains(e.target))closeSelect(false)},true);


applyTheme(preference);hydrate();
})();
